---
- hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - git
    - apache
    - mysql
    - php
    - php-phalcon
    - xdebug
    - composer
    - node