- name: Install application deps
  apt: pkg={{item}} state=installed
  become: yes
  become_user: root
  with_items:
    - npm

- name: "16.04 has opinions about node's name"
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  become: yes
  become_user: root

- name: Install Gulp + Bower
  npm: "name={{item}} global=yes"
  with_items:
      - bower
      - gulp
      - grunt-cli